//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MintyPeterson.Counter.Api.Services.Storage.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Queries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Queries() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MintyPeterson.Counter.Api.Services.Storage.Resources.Queries", typeof(Queries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --
        ///-- DESCRIPTION
        ///--   Updates an entry in the users table to mark the
        ///--   row as deleted.
        ///--
        ///-- PARAMETERS
        ///--   @EntryID - The entry identifier.
        ///--   @DeletedDateTime - The time the entry was deleted.
        ///--   @DeletedByUserID - The identifier of the user who deleted the entry.
        ///--
        ///-- OUTPUTS
        ///--   EntryID - The identifier of the updated entry.
        ///--
        ///UPDATE
        ///  Entries
        ///SET
        ///  Entries.DeletedDateTime = @DeletedDateTime
        /// ,Entries.DeletedByUserID = @DeletedByUserID
        ///OUTPUT
        ///  Inserted.EntryID
        ///WHERE
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EntryDeleteUpdate {
            get {
                return ResourceManager.GetString("EntryDeleteUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --
        ///-- DESCRIPTION
        ///--   Selects an entry.
        ///--
        ///-- PARAMETERS
        ///--   @EntryID - The entry identifier.
        ///--
        ///-- OUTPUTS
        ///--   EntryID - The entry identifier.
        ///--   CreatedDateTime - The time the entry was created.
        ///--   CreatedByUserID - The identifer of the user who created the entry.
        ///--   UpdatedDateTime - The time the entry was updated.
        ///--   UpdatedByUserID - The identifer of the user who updated the entry.
        ///--   EntryDate -  The entry date.
        ///--   Entry - The entry.
        ///--   Notes - Any notes or comments.
        ///- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EntryGetSelect {
            get {
                return ResourceManager.GetString("EntryGetSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --
        ///-- DESCRIPTION
        ///--   Inserts a new entry into the entries table.
        ///--
        ///-- PARAMETERS
        ///--   @CreatedDateTime - The time the entry was created.
        ///--   @CreatedByUserID - The identifier of the user who created the entry.
        ///--   @EntryDate - The entry date.
        ///--   @Entry - The entry.
        ///--   @Notes - Any notes or comments.
        ///--
        ///-- OUTPUTS
        ///--   EntryID - The identifier of the newly created entry.
        ///--
        ///INSERT INTO Entries (
        ///  EntryID
        /// ,CreatedDateTime
        /// ,CreatedByUserID
        /// ,UpdatedDateTime
        /// ,UpdatedByUserID
        /// ,E [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EntryNewInsert {
            get {
                return ResourceManager.GetString("EntryNewInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --
        ///-- DESCRIPTION
        ///--   Inserts a user in the users table.
        ///--
        ///-- PARAMETERS
        ///--   @UserID - The user subject identifier.
        ///--   @Name - The full name.
        ///--   @Email - The e-mail address.
        ///--   @UpdatedDateTime - The time the user was updated.
        ///--
        ///-- OUTPUTS
        ///--   None
        ///--
        ///INSERT INTO Users (
        ///  UserID
        /// ,[Name]
        /// ,Email
        /// ,CreatedDateTime
        /// ,UpdatedDateTime
        ///)
        ///VALUES(
        ///  @UserID
        /// ,@Name
        /// ,@Email
        /// ,@UpdatedDateTime
        /// ,@UpdatedDateTime
        ///).
        /// </summary>
        internal static string UserSynchroniseInsert {
            get {
                return ResourceManager.GetString("UserSynchroniseInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --
        ///-- DESCRIPTION
        ///--   Updates a user in the users table.
        ///--
        ///-- PARAMETERS
        ///--   @UserID - The user subject identifier.
        ///--   @Name - The full name.
        ///--   @Email - The e-mail address.
        ///--   @UpdatedDateTime - The time the user was updated.
        ///--
        ///-- OUTPUTS
        ///--   None
        ///--
        ///UPDATE
        ///  Users WITH (UPDLOCK, SERIALIZABLE)
        ///SET
        ///  Users.UpdatedDateTime = @UpdatedDateTime
        /// ,Users.[Name] = @Name
        /// ,Users.Email = @Email
        ///WHERE
        ///  Users.UserID = @UserID.
        /// </summary>
        internal static string UserSynchroniseUpdate {
            get {
                return ResourceManager.GetString("UserSynchroniseUpdate", resourceCulture);
            }
        }
    }
}
